### ISSUE TITLE
Add blog to header of main site

### ISSUE THREAD

**Issue by ToffeeMax** [Gamemode4Dev/gm4.co#18]

**Comment by Bloo-dev** [comment]
![image](https://user-images.githubusercontent.com/41843855/197048269-2809c0f8-d527-4a2c-8d05-4c2711870111.png)
We'll have to think about where to put it, because we can't go much wider to stay compatible with mobile devices.

However, we could move one of the current header links to a clickable slideshow image or add the blog as a clickable slideshow image (technically `server` already is on the slideshow, so does it have to be on the header?).

**Comment by ToffeeMax** [comment]
Just noting this here since we spoke:
- We should maintain the best experience across mobile and desktop
- We are agreeing (but not firm) on replacing "Server" with "Blog"

Personal note:
- Could we A/B test the changes?

Even further:
- Does the header need a complete change?
- Should we add a compact "Hamburger" on mobile?

**Comment by Bloo-dev** [comment]
We have replaced 'Modules' with 'Blog', as 'Modules' didn't actually have a lot to it, it simply scrolled the page down.
